CREATE TABLE IF NOT EXISTS users (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH TEXT NOT NULL,
    ROLE VARCHAR(64) DEFAULT 'USER' CHECK (ROLE IN ('USER', 'ADMIN')),
    NAME VARCHAR(255) NOT NULL CHECK (NAME <> ''),
    AGE INT NOT NULL CHECK (AGE > 12)
);

CREATE TABLE IF NOT EXISTS notes (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    USER_EMAIL VARCHAR(100) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
FOREIGN KEY (USER_EMAIL) REFERENCES users(EMAIL) ON DELETE CASCADE
);
